### ISSUE TITLE
2 datasets selected when edit pressed causes the database metadata to be edited

### ISSUE THREAD

**Issue by apmallo** [Esri/arcgis-pro-metadata-toolkit#7]
we select two datasets en press the edit metadata button, the shown metadata is the metadata of the database. We expected that two tabs would be opened each showing one of the selected datasets.

**Comment by aleta15** [comment]
@apmallo This is a bug in the core ArcGIS Pro software, and is not specific to the metadata toolkit or to a custom metadata style provided by an add-in. This is an issue in our internal backlog. If you submit an issue for this through Salesforce I can attach a BUG# to it so you can track the progress for that issue.
